I'm sorry to hear that you lost your work. It's always frustrating when that happens. 

Unfortunately, if the checkpoint file is blank, it's unlikely that you'll be able to recover your work. However, there are a few things you can try:

1. Check if there are any backup files in the same directory as your notebook. Jupyter Notebook creates backup files with the extension `.ipynb~`. If you find one, rename it to remove the `~` and try opening it.

2. Check if there are any other checkpoint files in the `.ipynb_checkpoints` folder. Jupyter Notebook creates a new checkpoint file every time you save, so there may be other checkpoint files that are more recent than the one you tried opening.

3. Check if there are any temporary files in the same directory as your notebook. Jupyter Notebook creates temporary files with the extension `.ipynb.tmp` while you're working on a notebook. If you find one, rename it to remove the `.tmp` extension and try opening it.

4. If you're using a version control system like Git, check if you committed your changes before closing the notebook. You may be able to recover your work from a previous commit.

In the future, you may want to consider using a cloud-based notebook service like Google Colab or Microsoft Azure Notebooks, which automatically save your work every few minutes. Alternatively, you can set Jupyter Notebook to autosave more frequently by adding the following line to your `jupyter_notebook_config.py` file:

```
c.NotebookApp.autosave_interval = 60 # Autosave every 60 seconds
```

I hope this helps!